#!/usr/bin/env python3
"""
BLE GATT Mirror Server (No MAC Cloning)

Starts a local BLE GATT peripheral on the Pi using a profile generated by
ble-proxy-profiler.py. The local peripheral uses the Pi's native controller
identity (different MAC is expected and allowed).

Current scope (step 3 + logging hooks):
  - Load profiled services/characteristics
  - Expose local GATT server via BlueZ (bless backend)
  - Handle local read/write requests with structured logging
  - Maintain local characteristic values in-memory

Planned next scope (step 4/5):
  - Forward reads/writes to the real target connection
  - Relay notifications/indications between target and client

Usage:
  sudo /opt/isolator/venv/bin/python3 /opt/isolator/scripts/ble-gatt-mirror.py \
      --profile /var/log/isolator/ble/profiles/profile_foo_latest.json
"""

import argparse
import asyncio
import json
import logging
import signal
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from bless import BlessServer
    from bless.backends.attribute import GATTAttributePermissions
    from bless.backends.characteristic import GATTCharacteristicProperties
except ImportError:
    print(
        "ERROR: bless is not installed. Install in Pi venv with:\n"
        "  /opt/isolator/venv/bin/pip install bless",
        file=sys.stderr,
    )
    sys.exit(1)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s'
)
logger = logging.getLogger('ble-gatt-mirror')

# Isolator Mirror Control Service UUIDs — project-specific, not Bluetooth SIG.
# Always advertised so the proxy is identifiable on a BLE scanner regardless of
# whether the profile contains GATT data.
_ISOLATOR_CTRL_SVC_UUID  = 'a1b2c3d4-0001-0001-0001-a1b2c3d4e5f6'
_ISOLATOR_CTRL_CHAR_UUID = 'a1b2c3d4-0001-0001-0002-a1b2c3d4e5f6'


@dataclass
class MirrorCharacteristic:
    service_uuid: str
    char_uuid: str
    properties: List[str]
    initial_value: bytearray


class BLEGATTMirror:
    def __init__(
        self,
        profile_path: Path,
        local_name: Optional[str],
        log_dir: Path,
        reconnect_target: bool = True,
        disconnect_on_target_loss: bool = False,
        disconnect_on_client_loss: bool = False,
    ):
        self.profile_path = profile_path
        self.local_name_override = local_name
        self.log_dir = log_dir
        self.log_dir.mkdir(parents=True, exist_ok=True)

        ts = datetime.now().strftime('%Y%m%d_%H%M%S')
        self.ops_log_file = self.log_dir / f'mirror_ops_{ts}.jsonl'

        self.profile: Dict[str, Any] = {}
        self.server: Optional[BlessServer] = None

        # char_uuid -> MirrorCharacteristic
        self.char_map: Dict[str, MirrorCharacteristic] = {}

        # char_uuid -> bytearray runtime value
        self.values: Dict[str, bytearray] = {}

        # Reconnect / behaviour flags
        self.reconnect_target = reconnect_target
        self.disconnect_on_target_loss = disconnect_on_target_loss
        self.disconnect_on_client_loss = disconnect_on_client_loss

        # Upstream (target device) connection state
        self.target_mac: Optional[str] = None
        self.target_client = None   # BleakClient assigned at runtime
        self.target_connected = False

        # Local (client → mirror) connection tracking
        self.client_was_connected = False

        self.running = True

    # ---------------------------- Profile parsing ----------------------------

    def _load_profile(self):
        with open(self.profile_path, 'r', encoding='utf-8') as f:
            self.profile = json.load(f)

        mode = self.profile.get('mode')
        if mode != 'ble-gatt-proxy-no-mac-clone':
            logger.warning(f"Profile mode is '{mode}', expected ble-gatt-proxy-no-mac-clone")

        gatt = self.profile.get('gatt', {})
        services = gatt.get('services', [])

        for svc in services:
            svc_uuid = str(svc.get('uuid', '')).strip()
            if not svc_uuid:
                continue

            for ch in svc.get('characteristics', []):
                ch_uuid = str(ch.get('uuid', '')).strip()
                if not ch_uuid:
                    continue

                props = list(ch.get('properties', []) or [])

                # Seed value from profiled read if available.
                read = ch.get('read', {}) or {}
                value_hex = read.get('value_hex') if read.get('ok') else None
                initial = bytearray.fromhex(value_hex) if value_hex else bytearray()

                mc = MirrorCharacteristic(
                    service_uuid=svc_uuid,
                    char_uuid=ch_uuid,
                    properties=props,
                    initial_value=initial,
                )
                self.char_map[ch_uuid] = mc
                self.values[ch_uuid] = bytearray(initial)

        logger.info(
            f"Loaded profile: services={len(services)} mirrored_chars={len(self.char_map)}"
        )

    @staticmethod
    def _props_to_flags(props: List[str]) -> GATTCharacteristicProperties:
        flags = GATTCharacteristicProperties(0)

        mapping = {
            'read': GATTCharacteristicProperties.read,
            'write': GATTCharacteristicProperties.write,
            'write-without-response': GATTCharacteristicProperties.write_without_response,
            'write_without_response': GATTCharacteristicProperties.write_without_response,
            'notify': GATTCharacteristicProperties.notify,
            'indicate': GATTCharacteristicProperties.indicate,
            'broadcast': GATTCharacteristicProperties.broadcast,
            'authenticated-signed-writes': GATTCharacteristicProperties.authenticated_signed_writes,
            'authenticated_signed_writes': GATTCharacteristicProperties.authenticated_signed_writes,
            'reliable-write': GATTCharacteristicProperties.reliable_write,
            'reliable_write': GATTCharacteristicProperties.reliable_write,
            'extended-properties': GATTCharacteristicProperties.extended_properties,
            'extended_properties': GATTCharacteristicProperties.extended_properties,
            'writable-auxiliaries': GATTCharacteristicProperties.writable_auxiliaries,
            'writable_auxiliaries': GATTCharacteristicProperties.writable_auxiliaries,
        }

        for p in props:
            key = str(p).strip().lower()
            if key in mapping:
                flags |= mapping[key]

        # Bless requires at least one property; default to read.
        if int(flags) == 0:
            flags = GATTCharacteristicProperties.read

        return flags

    @staticmethod
    def _permissions_for_props(props: List[str]) -> GATTAttributePermissions:
        perms = GATTAttributePermissions(0)

        can_read = any(p in props for p in ['read'])
        can_write = any(
            p in props for p in ['write', 'write-without-response', 'write_without_response']
        )

        if can_read:
            perms |= GATTAttributePermissions.readable
        if can_write:
            perms |= GATTAttributePermissions.writeable

        if int(perms) == 0:
            perms = GATTAttributePermissions.readable

        return perms

    # ------------------------------ Logging ---------------------------------

    def _log_op(self, op: Dict[str, Any]):
        op.setdefault('timestamp', datetime.now().isoformat())
        with open(self.ops_log_file, 'a', encoding='utf-8') as f:
            f.write(json.dumps(op) + '\n')

    # ---------------------------- GATT handlers -----------------------------

    def _read_request(self, char_uuid: str, _options: Optional[Dict] = None) -> bytearray:
        value = self.values.get(char_uuid, bytearray())
        self._log_op({
            'direction': 'client_to_mirror',
            'op': 'read',
            'char_uuid': char_uuid,
            'value_hex': value.hex(),
            'len': len(value),
        })
        return value

    def _write_request(self, char_uuid: str, value: Any):
        if isinstance(value, bytearray):
            raw = value
        elif isinstance(value, bytes):
            raw = bytearray(value)
        elif isinstance(value, str):
            raw = bytearray(value.encode('utf-8'))
        else:
            # Best effort coercion
            try:
                raw = bytearray(value)
            except Exception:
                raw = bytearray()

        self.values[char_uuid] = raw
        self._log_op({
            'direction': 'client_to_mirror',
            'op': 'write',
            'char_uuid': char_uuid,
            'value_hex': raw.hex(),
            'len': len(raw),
        })

    # ------------------------- Target reconnect -------------------------

    def _on_target_disconnected(self, _client) -> None:
        self.target_connected = False
        logger.warning(f'Target {self.target_mac} disconnected')
        self._log_op({'event': 'target_disconnected', 'mac': self.target_mac})
        if self.disconnect_on_target_loss:
            logger.info('--disconnect-on-target-loss: stopping mirror server')
            self.running = False
            try:
                asyncio.get_event_loop().create_task(self.stop())
            except RuntimeError:
                pass  # loop already stopped; run_forever cleanup will call stop()

    async def _connect_target(self) -> None:
        from bleak import BleakClient
        logger.info(f'Connecting to target {self.target_mac}...')
        client = BleakClient(
            self.target_mac,
            disconnected_callback=self._on_target_disconnected,
        )
        await client.connect(timeout=15.0)
        self.target_client = client
        self.target_connected = True
        logger.info(f'Target {self.target_mac} connected')
        self._log_op({'event': 'target_connected', 'mac': self.target_mac})

    async def _disconnect_target(self) -> None:
        client = self.target_client
        self.target_client = None
        self.target_connected = False
        if client is not None:
            try:
                await client.disconnect()
            except Exception as e:
                logger.debug(f'Target disconnect error (ignored): {e}')

    async def _target_connection_loop(self) -> None:
        """Connect to the real target device; optionally keep reconnecting on drop."""
        if not self.target_mac:
            return
        retry_delay = 5
        first_attempt = True
        while self.running:
            if not self.target_connected:
                if not first_attempt and not self.reconnect_target:
                    logger.info('Target connection lost; auto-reconnect disabled')
                    break
                try:
                    await self._connect_target()
                    first_attempt = False
                    retry_delay = 5
                except Exception as e:
                    first_attempt = False
                    if not self.reconnect_target:
                        logger.error(f'Target connect failed: {e}; auto-reconnect disabled')
                        break
                    logger.warning(f'Target connect failed: {e}; retry in {retry_delay}s')
                    await asyncio.sleep(retry_delay)
                    retry_delay = min(retry_delay * 2, 60)  # exponential back-off, cap 60s
            else:
                await asyncio.sleep(2)

    async def _client_watch_loop(self) -> None:
        """Detect local BLE client connect/disconnect from the mirror."""
        while self.running:
            await asyncio.sleep(1)
            if self.server is None:
                continue
            try:
                now_connected = await self.server.is_connected()
            except Exception:
                continue
            if self.client_was_connected and not now_connected:
                logger.info('Local BLE client disconnected from mirror')
                self._log_op({'event': 'client_disconnected'})
                if self.disconnect_on_client_loss:
                    logger.info('--disconnect-on-client-loss: dropping target connection')
                    await self._disconnect_target()
            elif not self.client_was_connected and now_connected:
                logger.info('Local BLE client connected to mirror')
                self._log_op({'event': 'client_connected'})
            self.client_was_connected = now_connected

    # ------------------------------ Runtime ---------------------------------

    async def start(self):
        self._load_profile()
        self.target_mac = self.profile.get('target', {}).get('mac')

        target_name = (
            self.profile.get('target', {}).get('name')
            or self.profile.get('target', {}).get('mac')
            or 'BLE-Mirror'
        )
        local_name = self.local_name_override or f"Mirror-{target_name}"[:29]

        self.server = BlessServer(name=local_name)

        # Hook read/write handlers so every operation is captured.
        self.server.read_request_func = self._read_request
        self.server.write_request_func = self._write_request

        # Add services and mirrored characteristics.
        services_seen = set()
        for mc in self.char_map.values():
            if mc.service_uuid not in services_seen:
                await self.server.add_new_service(mc.service_uuid)
                services_seen.add(mc.service_uuid)

            props = self._props_to_flags(mc.properties)
            perms = self._permissions_for_props(mc.properties)
            await self.server.add_new_characteristic(
                mc.service_uuid,
                mc.char_uuid,
                props,
                bytearray(mc.initial_value),
                perms,
            )

        # Always register the Isolator Mirror Control service.  This guarantees
        # BlueZ has at least one registered service (required) and makes the proxy
        # identifiable on any BLE scanner regardless of profile contents.
        await self.server.add_new_service(_ISOLATOR_CTRL_SVC_UUID)
        await self.server.add_new_characteristic(
            _ISOLATOR_CTRL_SVC_UUID,
            _ISOLATOR_CTRL_CHAR_UUID,
            GATTCharacteristicProperties.read | GATTCharacteristicProperties.write,
            bytearray(b'mirror-ready'),
            GATTAttributePermissions.readable | GATTAttributePermissions.writeable,
        )
        services_seen.add(_ISOLATOR_CTRL_SVC_UUID)
        self.char_map[_ISOLATOR_CTRL_CHAR_UUID] = MirrorCharacteristic(
            service_uuid=_ISOLATOR_CTRL_SVC_UUID,
            char_uuid=_ISOLATOR_CTRL_CHAR_UUID,
            properties=['read', 'write'],
            initial_value=bytearray(b'mirror-ready'),
        )
        self.values[_ISOLATOR_CTRL_CHAR_UUID] = bytearray(b'mirror-ready')
        if set(self.char_map) == {_ISOLATOR_CTRL_CHAR_UUID}:
            logger.warning('Profile had no GATT services; only control service registered')

        started = await self.server.start()
        if not started:
            raise RuntimeError('Bless server failed to start')

        logger.info('BLE mirror server started')
        logger.info(f'  Local name : {local_name}')
        logger.info(f'  Services   : {len(services_seen)}')
        logger.info(f'  Chars      : {len(self.char_map)}')
        logger.info(f'  Ops log    : {self.ops_log_file}')
        if self.target_mac:
            logger.info(f'  Target MAC : {self.target_mac}')
            logger.info(f'  Reconnect  : {self.reconnect_target}')
            logger.info(f'  On target loss : {"stop mirror" if self.disconnect_on_target_loss else "keep mirror (stale values)"}')
            logger.info(f'  On client loss : {"drop target" if self.disconnect_on_client_loss else "keep target"}')
        else:
            logger.info('  Target MAC : none (passive mode — no upstream forwarding)')

    async def stop(self):
        self.running = False
        await self._disconnect_target()
        if self.server is not None:
            try:
                await self.server.stop()
            except Exception as e:
                logger.warning(f'Error stopping server: {e}')
        logger.info('BLE mirror server stopped')

    async def run_forever(self):
        await self.start()

        loop = asyncio.get_running_loop()

        def _sig_handler(sig_name: str):
            logger.info(f'Signal {sig_name} received, shutting down...')
            asyncio.create_task(self.stop())

        for sig in (signal.SIGINT, signal.SIGTERM):
            try:
                loop.add_signal_handler(sig, _sig_handler, sig.name)
            except NotImplementedError:
                pass

        bg_tasks = [asyncio.create_task(self._client_watch_loop())]
        if self.target_mac:
            bg_tasks.append(asyncio.create_task(self._target_connection_loop()))

        while self.running:
            await asyncio.sleep(0.5)

        for t in bg_tasks:
            t.cancel()
        await asyncio.gather(*bg_tasks, return_exceptions=True)


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Start local BLE GATT mirror server from a profiler JSON (no MAC clone).'
    )
    parser.add_argument('--profile', required=True, help='Path to profile_*.json')
    parser.add_argument('--name', help='Override local advertised name')
    parser.add_argument(
        '--log-dir',
        default='/var/log/isolator/ble/proxy',
        help='Directory for mirror operation logs',
    )
    parser.add_argument(
        '--no-reconnect-target',
        action='store_true',
        help='Disable auto-reconnect to target if connection drops (default: reconnect)',
    )
    parser.add_argument(
        '--disconnect-on-target-loss',
        action='store_true',
        help='Stop local mirror server when the upstream target connection drops',
    )
    parser.add_argument(
        '--disconnect-on-client-loss',
        action='store_true',
        help='Drop upstream target connection when the local BLE client disconnects from the mirror',
    )

    args = parser.parse_args()

    mirror = BLEGATTMirror(
        profile_path=Path(args.profile),
        local_name=args.name,
        log_dir=Path(args.log_dir),
        reconnect_target=not args.no_reconnect_target,
        disconnect_on_target_loss=args.disconnect_on_target_loss,
        disconnect_on_client_loss=args.disconnect_on_client_loss,
    )

    try:
        asyncio.run(mirror.run_forever())
        return 0
    except KeyboardInterrupt:
        return 0
    except Exception as e:
        logger.error(f'Fatal mirror error: {e}', exc_info=True)
        return 1


if __name__ == '__main__':
    sys.exit(main())
