#!/usr/bin/env python3
"""
BLE GATT Mirror Server (No MAC Cloning)

Starts a local BLE GATT peripheral on the Pi using a profile generated by
ble-proxy-profiler.py. The local peripheral uses the Pi's native controller
identity (different MAC is expected and allowed).

Current scope (step 3 + logging hooks):
	- Load profiled services/characteristics
	- Expose local GATT server via BlueZ (bless backend)
	- Handle local read/write requests with structured logging
	- Maintain local characteristic values in-memory

Planned next scope (step 4/5):
	- Forward reads/writes to the real target connection
	- Relay notifications/indications between target and client

Usage:
	sudo /opt/PerimeterControl/venv/bin/python3 /opt/PerimeterControl/scripts/ble-gatt-mirror.py \
			--profile /var/log/PerimeterControl/ble/profiles/profile_foo_latest.json
"""

import argparse
import asyncio
import json
import logging
import signal
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
	from bless import BlessServer
	from bless.backends.attribute import GATTAttributePermissions
	from bless.backends.characteristic import GATTCharacteristicProperties
except ImportError:
	print(
		"ERROR: bless is not installed. Install in Pi venv with:\n"
		"  /opt/PerimeterControl/venv/bin/pip install bless",
		file=sys.stderr,
	)
	sys.exit(1)

logging.basicConfig(
	level=logging.INFO,
	format='%(asctime)s [%(levelname)s] %(message)s'
)
logger = logging.getLogger('ble-gatt-mirror')

# Isolator Mirror Control Service UUIDs — project-specific, not Bluetooth SIG.
# Always advertised so the proxy is identifiable on a BLE scanner regardless of
# whether the profile contains GATT data.

# ─── Configurable Constants ─────────────────────────────────────────────
import os
PERIMETERCONTROL_CTRL_SVC_UUID = os.environ.get('PERIMETERCONTROL_CTRL_SVC_UUID', 'a1b2c3d4-0001-0001-0001-a1b2c3d4e5f6')
PERIMETERCONTROL_CTRL_CHAR_UUID = os.environ.get('PERIMETERCONTROL_CTRL_CHAR_UUID', 'a1b2c3d4-0001-0001-0002-a1b2c3d4e5f6')
PERIMETERCONTROL_LOG_DIR = os.environ.get('PERIMETERCONTROL_LOG_DIR', '/var/log/PerimeterControl/ble/proxy')


@dataclass
class MirrorCharacteristic:
	service_uuid: str
	char_uuid: str
	properties: List[str]
	initial_value: bytearray


class BLEGATTMirror:
	def __init__(
		self,
		profile_path: Path,
		local_name: Optional[str],
		log_dir: Path,
		reconnect_target: bool = True,
		disconnect_on_target_loss: bool = False,
		disconnect_on_client_loss: bool = False,
	):
		self.profile_path = profile_path
		self.local_name_override = local_name
		self.log_dir = log_dir
		self.log_dir.mkdir(parents=True, exist_ok=True)

		ts = datetime.now().strftime('%Y%m%d_%H%M%S')
		self.ops_log_file = self.log_dir / f'mirror_ops_{ts}.jsonl'

		self.profile: Dict[str, Any] = {}
		self.server: Optional[BlessServer] = None

		# char_uuid -> MirrorCharacteristic
		self.char_map: Dict[str, MirrorCharacteristic] = {}

		# char_uuid -> bytearray runtime value
		self.values: Dict[str, bytearray] = {}

		# Reconnect / behaviour flags
		self.reconnect_target = reconnect_target
		self.disconnect_on_target_loss = disconnect_on_target_loss
		self.disconnect_on_client_loss = disconnect_on_client_loss

		# Upstream (target device) connection state
		self.target_mac: Optional[str] = None
		self.target_client = None   # BleakClient assigned at runtime
		self.target_connected = False

		# Local (client → mirror) connection tracking
		self.client_was_connected = False

		self.running = True

	# ...existing code from scripts/ble-gatt-mirror.py...
